Blog.WebUI/ViewModels/ArticleViewModels/ArticleViewModel.cs
using System;
using System.Collections.Generic;
using Blog.Business.Models.DTO;

namespace Blog.WebUI.ViewModels.ArticleViewModels
{
    public class ArticleViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public DateTime PublishDate { get; set; }

        public string Text { get; set; }

        public ICollection<TagModel> Tags { get; set; }
    }
}

Blog.WebUI/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Blog.Business.Infrastructure;
using Blog.Business.Models.DTO;
using Blog.Business.Models.QuestionaryAnswerModels;
using Blog.Business.Models.VoteModels;
using Blog.Business.Services.Interfaces;
using Blog.WebUI.ViewModels.ArticleViewModels;
using Blog.WebUI.ViewModels.VoteViewModels;

namespace Blog.WebUI.Controllers
{
    public class ArticlesController : Controller
    {
        private const int SymbolsForPreviewShow = 200;
        private const string HasVotedCookieString = "HasVoted";


        private static Dictionary<NetTechnologies, string> StringLabelForTechnologies => new Dictionary<NetTechnologies, string>
        {
            [NetTechnologies.AspNetMvc] = "ASP.NET MVC",
            [NetTechnologies.Wcf] = "WCF",
            [NetTechnologies.Wpf] = "WPF",
            [NetTechnologies.WebApi] = "Web Api"
        }; 


        private readonly IArticlesService _articlesService;
        private readonly IVoteService _voteService;

        public ArticlesController(
            IArticlesService articlesService,
            IVoteService voteService)
        {
            _articlesService = articlesService;
            _voteService = voteService;
        }

        [HttpGet]
        public async Task<ActionResult> Index()
        {
            var articlesViewModel = new ArticlesListViewModel
            {
                Articles = Mapper.Map<IEnumerable<ArticleModel>, IEnumerable<ArticleViewModel>>
                                                            (await _articlesService.GetArticlesAsync()),

                UserHasVoted = HttpContext.Request.Cookies[HasVotedCookieString] != null,


                Voice = new CreateVoiceViewModel
                {
                    RadioAnswersAndLabels = StringLabelForTechnologies
                },
            };

            if (articlesViewModel.UserHasVoted)
            {
                var voteResults = await _voteService.GetVoteResults();
                articlesViewModel.VoteResults = new VoteResultsViewModel
                {
                    Results = VoteAnswersToStatistics(voteResults)
                };
            }

            foreach (var article in articlesViewModel.Articles)
            {
                if (article.Text.Length > SymbolsForPreviewShow)
                {
                    article.Text = CutToLastWord(article.Text, SymbolsForPreviewShow);
                }
            }

            return View(articlesViewModel);
        }

        [HttpGet]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var article = await _articlesService.GetArticleAsync(id.Value);

            if (article == null)
            {
                return HttpNotFound();
            }

            var articleVm = Mapper.Map<ArticleModel, ArticleViewModel>(article);
            articleVm.Tags = (await _articlesService.GetArticleTags(id.Value)).ToList();

            return View(articleVm);
        }


        public async Task<ActionResult> MakeVote(CreateVoiceViewModel voice)
        {
            if (voice == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            await _voteService.AddVoice(Mapper.Map<CreateVoiceViewModel, VoiceModel>(voice));
            HttpContext.Response.Cookies.Add(new HttpCookie("HasVoted", bool.TrueString));

            return RedirectToAction(nameof(Index));
        }

        public async Task<ActionResult> MakeVoteAjax(CreateVoiceViewModel voice)
        {
            if (voice == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            await _voteService.AddVoice(Mapper.Map<CreateVoiceViewModel, VoiceModel>(voice));
            HttpContext.Response.Cookies.Add(new HttpCookie("HasVoted", bool.TrueString));

            return await GetVotePartialView();
        }

        private async Task<ActionResult> GetVotePartialView()
        {
            var answerStatistics = await _voteService.GetVoteResults();
            var voteResults = new VoteResultsViewModel
            {
                Results = VoteAnswersToStatistics(answerStatistics)
            };

            return PartialView("_VoteResultsPartial", voteResults);
        }

        #region Helpers

        private static string RemoveExtraSpaces(string text)
        {
            var arr = text.Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
            var resultCharArr = arr.SelectMany(str => str + ' ').ToArray();
            return new string(resultCharArr);
        }

        private static string CutToLastWord(string text, int substrLength)
        {
            var sb = new StringBuilder(text.Substring(0, substrLength));
            char[] separators = { ' ', '.', ',', ';', '!', '?' };

            for (var i = substrLength; i < text.Length && !separators.Contains(text[i]); i++)
            {
                sb.Append(text[i]);
            }

            sb.Append("...");
            return sb.ToString();
        }

        private static Statistics VoteAnswerToStatistics(VoteAnswerStatistics answer)
        {
            return new Statistics
            {
                Answer = StringLabelForTechnologies[answer.Answer],
                AnsweredCount = answer.AnsweredCount,
                AnsweredPercent = answer.AnsweredPercent
            };
        }

        private static IEnumerable<Statistics> VoteAnswersToStatistics(IEnumerable<VoteAnswerStatistics> answer)
        {
            return answer.Select(VoteAnswerToStatistics);
        }

        #endregion
    }
}

Blog.WebUI/Views/Article/Create.cshtml
@model Blog.WebUI.ViewModels.ArticleViewModels.ArticleViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ArticleViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PublishDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PublishDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PublishDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Articles")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Blog.WebUI/Views/Article/Edit.cshtml
@model Blog.WebUI.ViewModels.ArticleViewModels.ArticleViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Edit article</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PublishDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PublishDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PublishDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Articles")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}