Blog.WebUI/ViewModels/CommentViewModels/CommentViewModel.cs
using System;

namespace Blog.WebUI.ViewModels.CommentViewModels
{
    public class CommentViewModel
    {
        public int Id { get; set; }
        public string AuthorName { get; set; }
        public DateTime PublishDate { get; set; }
        public string Text { get; set; }
    }
}

Blog.WebUI/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;
using Blog.Business.Models.DTO;
using Blog.Business.Services.Interfaces;
using Blog.WebUI.ViewModels.CommentViewModels;

namespace Blog.WebUI.Controllers
{
    public class CommentsController : Controller
    {
        private readonly ICommentsService _commentsService;

        public CommentsController(ICommentsService commentsService)
        {
            _commentsService = commentsService;
        }

        [HttpGet]
        public async Task<ActionResult> Index()
        {
            var commentsViewModel = await GetOrderedList();

            return View(commentsViewModel);
        }

        [HttpPost]
        public async Task<ActionResult> CreateComment(CommentViewModel comment)
        {
            if (!ModelState.IsValid)
            {
                var commentsViewModel = await GetOrderedList(comment);

                return View("Index", commentsViewModel);
            }

            comment.PublishDate = DateTime.UtcNow;
            await _commentsService.CreateAsync(Mapper.Map<CommentViewModel, CommentModel>(comment));
            return RedirectToAction(nameof(Index));
        }


        #region Helpers

        private async Task<CommentsListViewModel> GetOrderedList(CommentViewModel commentToAdd = null)
        {
            var orderedComments = (await _commentsService.GetCommentsAsync())
                .OrderByDescending(c => c.PublishDate)
                .ToList();

            var commentsViewModel = new CommentsListViewModel
            {
                Comments = Mapper.Map<IEnumerable<CommentModel>, IEnumerable<CommentViewModel>>(orderedComments),
                CommentsCount = orderedComments.Count,
                CommentToAdd = commentToAdd ?? new CommentViewModel()
            };

            return commentsViewModel;
        }

        #endregion
    }
}

Blog.WebUI/Views/Comments/Index.cshtml
@model Blog.WebUI.ViewModels.CommentViewModels.CommentsListViewModel

<div class="wrapper">
    <div class="form-container">
        @Html.Partial("_CreateCommentPartial", Model.CommentToAdd)
    </div>
    <hr />
    <p>@Model.CommentsCount comment(s)</p>
    <hr />
    <div class="comments">
        @foreach (var comment in Model.Comments)
        {
            @Html.Partial("_CommentPartial", comment)
            <hr />
        }
    </div>
</div>

<link href="~/Content/comments.css" rel="stylesheet" />

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Blog.WebUI/Views/Comments/_CommentPartial.cshtml
@model Blog.WebUI.ViewModels.CommentViewModels.CommentViewModel

<div class="comment">
    <div class="comment-header">
        <p class="comment-author">@Model.AuthorName</p>
        <p class="publish-date">@Model.PublishDate</p>
    </div>
    <div class="comment-content">
        <p>@Model.Text</p>
    </div>
</div>

Blog.WebUI/Views/Comments/_CreateCommentPartial.cshtml
@model Blog.WebUI.ViewModels.CommentViewModels.CommentViewModel

@using (Html.BeginForm("CreateComment", "Comments", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Write your comment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.AuthorName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AuthorName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AuthorName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}